export const colonies = [
    { topic: '2000', name: '2000', dates: [{ day: 'Miércoles', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    { topic: '30_mayo', name: '30 de Mayo', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    //{ topic: '7_enero', name: '7 de Enero', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    { topic: 'alamos', name: 'Álamos', dates: [{ day: 'Martes', hour: 'Vespertino' }, { day: 'Jueves', hour: 'Matutino' }] },
    { topic: 'anahuac', name: 'Anáhuac', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    { topic: 'aquiles_serdan', name: 'Aquiles Serdán', dates: [{ day: 'Martes', hour: 'Vespertino' }, { day: 'Viernes', hour: 'Matutino' }] },
    //{ topic: 'arboledas', name: 'Arboledas', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    { topic: 'aurora', name: 'Aurora', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    //---{ topic: 'boteros', name: 'Boteros', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
   // { topic: 'juarez_limites', name: 'Av. Juarez Limites Rio Blanco', dates: [{ day: 'Miércoles', hour: 'Vespertino' }, { day: 'Viernes', hour: 'Matutino' }] },
    { topic: 'balastrera', name: 'Balastrera', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    { topic: 'campanario', name: 'Campanario', dates: [{ day: 'Miércoles', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    { topic: 'carranza', name: 'Carranza', dates: [{ day: 'Martes', hour: 'Vespertino' }, { day: 'Viernes', hour: 'Matutino' }] },
    //{ topic: 'centro_salud', name: 'Centro de salud', dates: [{ day: 'Miércoles', hour: 'Vespertino' }, { day: 'Viernes', hour: 'Matutino' }] },
    { topic: 'chapultepec', name: 'Chapultepec', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    //{ topic: 'clinica_pemex', name: 'Clinica de Pemex', dates: [{ day: 'Martes', hour: 'Vespertino' }, { day: 'Jueves', hour: 'Matutino' }] },
    { topic: 'corregidora', name: 'Corregidora', dates: [{ day: 'Miércoles', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    //{ topic: 'diconsa', name: 'Diconsa', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    { topic: 'el_aguila', name: 'El Águila', dates: [{ day: 'Lunes', hour: 'Vespertino' }, { day: 'Jueves', hour: 'Matutino' }] },
    { topic: 'el_arenal', name: 'El Arenal', dates: [{ day: 'Lunes', hour: 'Vespertino' }, { day: 'Miércoles', hour: 'Matutino' }] },
    { topic: 'el_cerrito', name: 'El Cerrito', dates: [{ day: 'Miércoles', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    { topic: 'escuelas', name: 'Escuelas', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Martes', hour: 'Matutino' }, { day: 'Miércoles', hour: 'Matutino' }, { day: 'Jueves', hour: 'Matutino' }, { day: 'Viernes', hour: 'Matutino' }] },
    //{ topic: 'encierro', name: 'Encierro', dates: [{ day: 'Sábado', hour: 'Vespertino' }] },
    { topic: 'encinar', name: 'Encinar', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    { topic: 'carrillo_puerto', name: 'Felipe Carrillo Puerto', dates: [{ day: 'Miércoles', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    { topic: 'guerrero', name: 'Guerrero', dates: [{ day: 'Lunes', hour: 'Vespertino' }, { day: 'Miércoles', hour: 'Matutino' }] },
    { topic: 'hermosa_provincia', name: 'Hermosa Provincia', dates: [{ day: 'Lunes', hour: 'Vespertino' }, { day: 'Miércoles', hour: 'Matutino' }] },
    { topic: 'la_carbonera', name: 'La Carbonera', dates: [{ day: 'Miércoles', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    //{ topic: 'la_corona', name: 'La Corona', dates: [{ day: 'Martes', hour: 'Vespertino' }, { day: 'Sábado', hour: 'Matutino' }] },
    //{ topic: 'la_laguna', name: 'La Laguna', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Sábado', hour: 'Matutino' }] },
    { topic: 'la_raya', name: 'La Raya', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    { topic: 'lazaro_cardenas', name: 'Lázaro Cárdenas', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    { topic: 'libertad', name: 'Libertad', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Lunes', hour: 'Vespertino' },{ day: 'Miércoles', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }] },
    { topic: 'lopez_arias', name: 'Lopez Arias',  dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    { topic: 'los_colorines', name: 'Los Colorines', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Viernes', hour: 'Vespertino' }]},
    { topic: 'los_fresnos', name: 'Los Fresnos', dates: [{ day: 'Lunes', hour: 'Vespertino' }, { day: 'Miércoles', hour: 'Matutino' }]},
    { topic: 'mirador', name: 'Mirador', dates: [{ day: 'Lunes', hour: 'Vespertino' }, { day: 'Miércoles', hour: 'Matutino' }] },
    { topic: 'nueva_rosita', name: 'Nueva Rosita', dates: [{ day: 'Martes', hour: 'Vespertino' }, { day: 'Jueves', hour: 'Matutino' }] },
    { topic: 'ojo_zarco', name: 'Ojo Zarco', dates: [{ day: 'Miércoles', hour: 'Vespertino' }, { day: 'Viernes', hour: 'Matutino' }] },
    { topic: 'paseo_nuevo', name: 'Paseo Nuevo', dates: [{ day: 'Martes', hour: 'Vespertino' }, { day: 'Jueves', hour: 'Matutino' }] },
    { topic: 'prolongacion', name: 'Prolongación Av. Juarez', dates: [{ day: 'Miércoles', hour: 'Vespertino' }, { day: 'Viernes', hour: 'Matutino' }] },
    { topic: 'rancho_viejo', name: 'Rancho Viejo', dates: [{ day: 'Miércoles', hour: 'Vespertino' }, { day: 'Viernes', hour: 'Matutino' }] },
    { topic: 'reforma', name: 'Reforma', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
    { topic: 's_isidro', name: 'San Isidro', dates: [{ day: 'Martes', hour: 'Vespertino' }, { day: 'Jueves', hour: 'Matutino' }] },
    { topic: 'taza_agua', name: 'Taza de Agua', dates: [{ day: 'Miércoles', hour: 'Vespertino' }, { day: 'Viernes', hour: 'Matutino' }] },
    { topic: 'union_progreso', name: 'Unión y Progreso', dates: [{ day: 'Martes', hour: 'Matutino' }, { day: 'Viernes', hour: 'Matutino' }] },
    { topic: 'vista_hermosa', name: 'Vista Hermosa', dates: [{ day: 'Lunes', hour: 'Matutino' }, { day: 'Jueves', hour: 'Vespertino' }] },
]
