export const colonies = [
    {topic: '2000', name: '2000'},
    { topic: '30_mayo', name:'30 de mayo'},
    { topic: '7_enero', name:'7 de enero'},
    { topic: 'alamos', name:'alamos'},
    { topic: 'anahuac', name:'anahuac'},
    { topic: 'aquiles_serdan', name:'aquiles serdan'},
    { topic: 'arboledas', name:'arboledas'},
    { topic: 'aurora', name:'aurora'},
    { topic: 'balastrera', name:'balastrera'},
    { topic: 'carranza', name:'carranza'},
    { topic: 'chapultepec', name:'chapultepec'},
    { topic: 'corregidora', name:'corregidora'},
    { topic: 'el_aguila', name:'el aguila'},
    { topic: 'el_arenal', name:'el arenal'},
    { topic: 'el_cerrito', name:'el cerrito'},
    { topic: 'encinar', name:'encinar'},
    { topic: 'carrillo_puerto', name:'carrillo puerto'},
    { topic: 'guerrero', name:'guerrero'},
    { topic: 'la_carbonera', name:'la carbonera'},
    { topic: 'libertad', name:'libertad'},
    { topic: 'lopez_arias', name:'lopez arias'},
    { topic: 'los_fresnos', name:'los fresnos'},
    { topic: 'mirador', name:'mirador'},
    { topic: 'nogales_centro', name:'nogales centro'},
    { topic: 'nueva_rosita', name:'nueva rosita'},
    { topic: 'ojo_zarco', name:'ojo zarco'},
    { topic: 'paseo_nuevo', name:'paseo nuevo'},
    { topic: 'provincia', name:'provincia'},
    { topic: 'reforma', name:'reforma'},
    { topic: 'taza_agua', name:'taza de agua'},
    { topic: 'union_progreso', name:'union y progreso'},
    { topic: 'vista_hermosa', name:'vista hermosa'},
]
